[package]
name = "eggserve-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
description = "Generic EggServe HTTP runtime and transport boundary"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
http2 = ["hyper/http2", "hyper-util/http2"]
tls = ["dep:rustls", "dep:tokio-rustls"]

[dependencies]
eggserve-primitives = { path = "../eggserve-primitives", version = "0.1.2" }
bytes = "1"
http-body = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio", "server", "http1"] }
tokio = { version = "1", features = ["macros", "net", "time", "io-util", "sync"] }
thiserror = "2"
rustls = { version = "0.23", optional = true, default-features = false, features = ["std", "ring"] }
tokio-rustls = { version = "0.26", optional = true, default-features = false, features = ["ring"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
