"""Type stubs for eggserve._native canonical request types."""

from typing import Any, Callable, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Base error types
# ---------------------------------------------------------------------------

class EggserveError(Exception): ...
class PathPolicyError(EggserveError): ...
class RequestTargetError(EggserveError): ...
class RequestValidationError(EggserveError): ...
class SecureRootError(EggserveError): ...
class BodySourceError(EggserveError): ...
class ResponseConstructionError(EggserveError): ...
class LifecycleError(EggserveError): ...

# ---------------------------------------------------------------------------
# Canonical request type errors
# ---------------------------------------------------------------------------

class MethodError(EggserveError): ...
class HttpVersionError(EggserveError): ...
class HeaderError(EggserveError): ...
class DuplicateHeaderError(EggserveError): ...

# ---------------------------------------------------------------------------
# Method (canonical HTTP method)
# ---------------------------------------------------------------------------

class Method:
    """A validated HTTP method (standard + extension)."""

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def get() -> Method: ...
    @staticmethod
    def head() -> Method: ...
    @staticmethod
    def post() -> Method: ...
    @staticmethod
    def put() -> Method: ...
    @staticmethod
    def delete() -> Method: ...
    @staticmethod
    def patch() -> Method: ...
    @property
    def as_str(self) -> str: ...
    @property
    def is_safe(self) -> bool: ...
    @property
    def is_idempotent(self) -> bool: ...
    @property
    def permits_static_resolution(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ---------------------------------------------------------------------------
# HttpVersion (canonical HTTP version)
# ---------------------------------------------------------------------------

class HttpVersion:
    """An HTTP version (HTTP/1.0 or HTTP/1.1)."""

    def __init__(self, value: str) -> None: ...
    @staticmethod
    def http10() -> HttpVersion: ...
    @staticmethod
    def http11() -> HttpVersion: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ---------------------------------------------------------------------------
# HeaderBlock (duplicate-preserving headers)
# ---------------------------------------------------------------------------

class HeaderBlock:
    """An ordered, duplicate-preserving collection of HTTP headers."""

    def __init__(self, fields: Optional[List[Tuple[str, str]]] = None) -> None: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def len(self) -> int: ...
    def get_first(self, name: str) -> Optional[str]: ...
    def get_all(self, name: str) -> List[str]: ...
    def get_unique(self, name: str) -> Optional[str]: ...
    def contains(self, name: str) -> bool: ...
    def iter(self) -> List[Tuple[str, str]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> List[Tuple[str, str]]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# ConnectionInfo (transport metadata)
# ---------------------------------------------------------------------------

class ConnectionInfo:
    """Transport metadata for a connection."""

    def __init__(
        self,
        local_addr: str,
        remote_addr: str,
        scheme: str = "http",
        tls_protocol_version: Optional[str] = None,
        tls_server_name: Optional[str] = None,
    ) -> None: ...
    @property
    def local_addr(self) -> str: ...
    @property
    def remote_addr(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def is_tls(self) -> bool: ...
    @property
    def tls_protocol_version(self) -> Optional[str]: ...
    @property
    def tls_server_name(self) -> Optional[str]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# CanonicalRequest (canonical HTTP request head)
# ---------------------------------------------------------------------------

class CanonicalRequest:
    """A canonical HTTP request head."""

    def __init__(
        self,
        method: str,
        path: str,
        version: str = "HTTP/1.1",
        headers: Optional[List[Tuple[str, str]]] = None,
        query: Optional[str] = None,
        remote_addr: Optional[str] = None,
        local_addr: Optional[str] = None,
        scheme: str = "http",
    ) -> None: ...
    @property
    def method(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> Optional[str]: ...
    @property
    def version(self) -> str: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def remote_addr(self) -> Optional[str]: ...
    @property
    def local_addr(self) -> Optional[str]: ...
    @property
    def scheme(self) -> str: ...
    @property
    def is_head(self) -> bool: ...
    @property
    def is_get(self) -> bool: ...
    def header_block(self) -> HeaderBlock: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Standalone parsing functions
# ---------------------------------------------------------------------------

def parse_method(value: str) -> Method: ...
def parse_http_version(value: str) -> HttpVersion: ...

# ---------------------------------------------------------------------------
# Server types
# ---------------------------------------------------------------------------

class Request:
    method: str
    path: str
    query: str
    headers: dict[str, str]
    remote_addr: str | None
    http_version: str
    has_body: bool

class Response:
    status: int
    headers: dict[str, str]
    @staticmethod
    def empty(status: int) -> Response: ...
    @staticmethod
    def bytes(status: int, data: bytes, headers: dict[str, str] | None = None) -> Response: ...
    @staticmethod
    def text(status: int, text: str, headers: dict[str, str] | None = None) -> Response: ...

class StaticPolicyWrapper:
    directory_listing: bool
    follow_symlinks: bool
    allow_dotfiles: bool
    def __init__(
        self,
        directory_listing: bool = False,
        follow_symlinks: bool = False,
        allow_dotfiles: bool = False,
    ) -> None: ...

class ServerSecureRoot:
    root_path: str
    def __init__(self, path: str, policy: StaticPolicyWrapper | None = None) -> None: ...

class StaticResponder:
    def __init__(self, root: ServerSecureRoot) -> None: ...
    def respond(
        self,
        method: str,
        target: str,
        headers: dict[str, str] | None = None,
        has_body: bool = False,
        remote_addr: str | None = None,
        http_version: str | None = None,
    ) -> Response: ...

class ServerBodySource:
    kind: str
    length: int | None
    range: tuple[int, int] | None
    def to_response(self, status: int = 200) -> Response: ...
    def read_all(self) -> bytes: ...
    def read_range(self, start: int, end_inclusive: int) -> bytes: ...

class Server:
    def __init__(
        self,
        root: str,
        bind: str = "127.0.0.1",
        port: int = 8000,
        policy: StaticPolicyWrapper | None = None,
        handler: Callable[[Request], Response] | None = None,
        public: bool = False,
        max_connections: int = 100,
        max_file_streams: int = 64,
        max_python_callbacks: int = 8,
        header_timeout_secs: int = 10,
        write_timeout_secs: int = 30,
        handler_timeout_secs: int = 30,
        graceful_shutdown_timeout_secs: int = 10,
    ) -> None: ...

    @property
    def addr(self) -> str | None: ...

    @property
    def state(self) -> str: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def wait_ready(self) -> None: ...

    def shutdown(self) -> None: ...

    def force_shutdown(self, timeout_secs: float = 10.0) -> str: ...

    def wait(self) -> str: ...

    def __enter__(self) -> Server: ...

    def __exit__(self, *args: Any) -> bool: ...
