"""Typing surface for the low-level in-process runtime."""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import (
    Any, AsyncIterable, AsyncIterator, Callable, Iterable, Iterator, Mapping,
    Optional, Sequence, TypeVar,
)

from eggserve._native import (
    BodySource, BodySourceError, BodyChunkIterator, ConnectionInfo,
    DuplicateHeaderError, EggserveError, HeaderBlock, HeaderError, HttpVersion,
    HttpVersionError, Method, MethodError, PathPolicy, PathPolicyError, Request,
    RequestBody, RequestBodyCancelledError, RequestBodyConsumedError,
    RequestBodyDisconnectedError, RequestBodyError, RequestBodyIncompleteError,
    RequestBodyRejectedError, RequestBodyTimeoutError, RequestBodyTooLargeError,
    RequestTarget, RequestTargetError, RequestValidationError, ResolvedDirectory,
    ResolvedFile, ResolvedResource, Response, ResponseConstructionError,
    SecureRoot, SecureRootError, StaticPolicy, generate_etag, parse_http_version,
    parse_method, validate_method, validate_request_body, validate_request_target,
)
from eggserve._native import (
    ServerBodySource, ServerRequestError, ServerSecureRoot,
    StaticPolicyWrapper, StaticResponder, TunnelRequest,
)

__all__ = [
    "BodySource", "BodySourceError", "BodyChunkIterator", "ConnectionInfo",
    "DuplicateHeaderError", "EggserveError", "HeaderBlock", "HeaderError",
    "HttpVersion", "HttpVersionError", "Method", "MethodError", "PathPolicy",
    "PathPolicyError", "Request", "RequestBody", "RequestBodyCancelledError",
    "RequestBodyConsumedError", "RequestBodyDisconnectedError", "RequestBodyError",
    "RequestBodyIncompleteError", "RequestBodyRejectedError", "RequestBodyTimeoutError",
    "RequestBodyTooLargeError", "RequestTarget", "RequestTargetError",
    "RequestValidationError", "ResolvedDirectory", "ResolvedFile", "ResolvedResource",
    "Response", "ResponseConstructionError", "SecureRoot", "SecureRootError",
    "StaticPolicy", "generate_etag", "parse_http_version", "parse_method",
    "validate_method", "validate_request_body", "validate_request_target",
    "RuntimeConfig", "Server", "ServerBodySource", "ServerRequestError",
    "ServerSecureRoot", "StaticPolicyWrapper", "StaticResponder", "AsyncServer",
    "AsyncRequest", "AsyncBody", "AsyncResponse", "AsyncTunnel", "AsyncTunnelCapability",
]

SyncHandler = Callable[[Request], Response]
BytesLike = bytes | bytearray | memoryview
AsyncBytesIterable = AsyncIterable[BytesLike] | Iterable[BytesLike]


@dataclass(frozen=True)
class RuntimeConfig:
    bind: str = ...
    port: int = ...
    public: bool = ...
    max_connections: int = ...
    max_file_streams: int = ...
    max_python_callbacks: int = ...
    max_in_flight_requests: int = ...
    header_timeout_secs: int = ...
    connection_total_timeout_secs: int = ...
    handler_timeout_secs: int = ...
    body_timeout_secs: int = ...
    graceful_shutdown_timeout_secs: int = ...
    keep_alive_idle_timeout_secs: int = ...
    max_requests_per_connection: int | None = ...
    response_write_timeout_secs: int = ...
    max_buf_size: int = ...
    max_headers: int = ...
    max_header_bytes: int = ...
    max_request_target_bytes: int = ...
    request_body_mode: str = ...
    max_request_body_bytes: int = ...
    tls_certfile: str | None = ...
    tls_keyfile: str | None = ...
    server_header: str | None = ...
    date_policy: str = ...
    stripped_response_headers: tuple[str, ...] = ...
    error_policy: str = ...
    trusted_proxies: tuple[str, ...] = ...
    trust_unix_local: bool = ...
    proxy_protocol: bool = ...
    forwarded_standard: bool = ...
    forwarded_legacy: bool = ...


class Server:
    def __init__(
        self,
        config: RuntimeConfig | None = ...,
        handler: SyncHandler | None = ...,
        *,
        _native: object | None = ...,
    ) -> None: ...
    @property
    def addr(self) -> tuple[str, int] | None: ...
    @property
    def state(self) -> str: ...
    def start(self) -> None: ...
    def wait_ready(self) -> None: ...
    def shutdown(self) -> None: ...
    def stop(self) -> None: ...
    def wait(self) -> Any: ...
    def force_shutdown(self, timeout_secs: float = ...) -> Any: ...
    def __enter__(self) -> Server: ...
    def __exit__(self, *args: object) -> bool: ...


class AsyncBody:
    def __init__(self, sync_body: RequestBody) -> None: ...
    @property
    def declared_length(self) -> int | None: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def complete(self) -> bool: ...
    async def aread(self) -> bytes: ...
    def aiter_chunks(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]: ...
    async def trailers(self) -> list[tuple[str, str]] | None: ...


class AsyncTunnel:
    def is_closed(self) -> bool: ...
    async def recv(self) -> bytes | None: ...
    async def send(self, data: BytesLike) -> None: ...
    def close(self) -> None: ...


class AsyncTunnelCapability:
    @property
    def kind(self) -> str: ...
    @property
    def protocol(self) -> str | None: ...
    @property
    def authority(self) -> str | None: ...
    def accept(
        self, headers: Sequence[tuple[str, str]] | None = ...
    ) -> tuple[Response, AsyncTunnel]: ...


class AsyncRequest:
    @property
    def method(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def header_items(self) -> list[tuple[str, str]]: ...
    @property
    def header_items_bytes(self) -> list[tuple[bytes, bytes]]: ...
    @property
    def raw_target_bytes(self) -> bytes: ...
    @property
    def path_bytes(self) -> bytes: ...
    @property
    def query_bytes(self) -> bytes | None: ...
    @property
    def http_version(self) -> str: ...
    @property
    def authority(self) -> str | None: ...
    @property
    def scheme(self) -> str | None: ...
    @property
    def remote_addr(self) -> str | None: ...
    @property
    def remote_address(self) -> tuple[str, int] | None: ...
    @property
    def local_addr(self) -> str | None: ...
    @property
    def local_address(self) -> tuple[str, int] | None: ...
    @property
    def effective_addr(self) -> str | None: ...
    @property
    def effective_address(self) -> tuple[str, int] | None: ...
    @property
    def effective_scheme(self) -> str | None: ...
    @property
    def effective_authority(self) -> str | None: ...
    @property
    def proxy_provenance(self) -> str | None: ...
    @property
    def forwarded_provenance(self) -> str | None: ...
    @property
    def proxy_source(self) -> str | None: ...
    @property
    def proxy_destination(self) -> str | None: ...
    @property
    def tls_protocol_version(self) -> str | None: ...
    @property
    def tls_server_name(self) -> str | None: ...
    @property
    def tls_alpn(self) -> str | None: ...
    @property
    def client_authenticated(self) -> bool: ...
    @property
    def peer_certificates_present(self) -> bool: ...
    @property
    def has_body(self) -> bool: ...
    @property
    def body(self) -> AsyncBody | None: ...
    def is_disconnected(self) -> bool: ...
    def cancellation_reason(self) -> str | None: ...
    async def wait_disconnected(self, timeout_secs: float | None = ...) -> bool: ...
    async def send_interim(
        self, status: int, headers: Sequence[tuple[str, str]] | None = ...
    ) -> str: ...
    def has_tunnel(self) -> bool: ...
    def tunnel_request(self) -> TunnelRequest | None: ...
    def take_tunnel(self) -> AsyncTunnelCapability | None: ...


class AsyncResponse:
    @staticmethod
    def empty(status: int) -> Response: ...
    @staticmethod
    def bytes(
        status: int, data: BytesLike, headers: Mapping[str, str] | None = ...
    ) -> Response: ...
    @staticmethod
    def text(
        status: int, text: str, headers: Mapping[str, str] | None = ...
    ) -> Response: ...
    @staticmethod
    def stream(
        status: int,
        async_iterable: AsyncBytesIterable,
        headers: Mapping[str, str] | None = ...,
        content_length: int | None = ...,
        trailers: Sequence[tuple[str, str]] | None = ...,
    ) -> object: ...


AsyncHandler = Callable[[AsyncRequest], Any]


class AsyncServer:
    def __init__(
        self,
        config: RuntimeConfig | None = ...,
        handler: AsyncHandler | None = ...,
        *,
        max_async_tasks: int | None = ...,
    ) -> None: ...
    @property
    def addr(self) -> tuple[str, int] | None: ...
    @property
    def max_async_tasks(self) -> int: ...
    async def start(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def __aenter__(self) -> AsyncServer: ...
    async def __aexit__(self, *args: object) -> bool: ...
    def track(self, task: asyncio.Task[Any]) -> asyncio.Task[Any]: ...
