from typing import Any

class BaseHTTPRequestHandler:
    server_version: str
    sys_version: str
    protocol_version: str
    client_address: tuple[str, int]
    command: str
    path: str
    request_version: str
    headers: Any
    rfile: Any
    wfile: Any
    def __init__(self, request: Any, client_address: tuple[str, int], server: Any) -> None: ...
    def send_response(self, code: int, message: str | None = None) -> None: ...
    def send_response_only(self, code: int, message: str | None = None) -> None: ...
    def send_header(self, keyword: str, value: str) -> None: ...
    def end_headers(self) -> None: ...
    def flush_headers(self) -> None: ...
    def send_error(self, code: int, message: str | None = None, explain: str | None = None) -> None: ...
    def version_string(self) -> str: ...
    def date_time_string(self, timestamp: float | None = None) -> str: ...
    def address_string(self) -> str: ...

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    directory: str | None
    index_pages: tuple[str, ...]
    directory_listing: bool
    follow_symlinks: bool
    allow_dotfiles: bool
    extensions_map: dict[str, str]
    def __init__(self, request: Any, client_address: tuple[str, int], server: Any, directory: str | None = ...) -> None: ...
    def do_GET(self) -> None: ...
    def do_HEAD(self) -> None: ...
    def send_head(self) -> Any: ...
    def guess_type(self, path: str) -> str: ...
    def list_directory(self, path: Any) -> Any: ...
    def translate_path(self, path: str) -> str: ...

class HTTPServer:
    RequestHandlerClass: type[BaseHTTPRequestHandler]
    server_address: tuple[str, int]
    server_name: str
    server_port: int
    def __init__(self, server_address: tuple[str, int], RequestHandlerClass: type[BaseHTTPRequestHandler], bind_and_activate: bool = True, *, max_request_body_bytes: int = ..., max_handler_response_bytes: int = ...) -> None: ...
    def serve_forever(self, poll_interval: float = 0.5) -> None: ...
    def shutdown(self) -> None: ...
    def server_close(self) -> None: ...
    def handle_request(self) -> None: ...
    def fileno(self) -> int: ...
    def __enter__(self) -> "HTTPServer": ...
    def __exit__(self, *args: Any) -> bool: ...

class ThreadingHTTPServer(HTTPServer):
    def __init__(self, server_address: tuple[str, int], RequestHandlerClass: type[BaseHTTPRequestHandler], bind_and_activate: bool = True, *, max_workers: int = 8, max_request_body_bytes: int = ..., max_handler_response_bytes: int = ...) -> None: ...

class HTTPSServer(HTTPServer):
    def __init__(self, server_address: tuple[str, int], RequestHandlerClass: type[BaseHTTPRequestHandler], bind_and_activate: bool = True, *, certfile: str, keyfile: str | None = ..., password: str | None = ..., alpn_protocols: list[str] | None = ..., max_request_body_bytes: int = ..., max_handler_response_bytes: int = ...) -> None: ...

class ThreadingHTTPSServer(HTTPSServer):
    def __init__(self, server_address: tuple[str, int], RequestHandlerClass: type[BaseHTTPRequestHandler], bind_and_activate: bool = True, *, certfile: str, keyfile: str | None = ..., password: str | None = ..., alpn_protocols: list[str] | None = ..., max_workers: int = 8, max_request_body_bytes: int = ..., max_handler_response_bytes: int = ...) -> None: ...
